---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
    author: kareem
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      labels:
        type: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
          volumeMounts:
           - name: my-volume
             mountPath: /usr/share/nginx/html
      volumes:
        - name: my-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30018
  selector: 
    type: proxy  

