---
apiVersion: v1
kind: service
metadata:
   name: myservice
   labels:
     author: kareem
spec:
   type: ClusterIP
   ports:
     - targetPort: 80
       port: 7777
   selector:
     type: proxy
       
       


