---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    type: db
    author: kareem
spec:
  replicas: 3
  selector:
    matchLabels: 
       type: db
  template: 
    metadata:
      name: mongodb-pod
      labels: 
        type: db
    spec: 
      containers:
        - name: mymongodb
          image: mongo
          ports: 
            - containerPort: 8081
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password    
            - name: MONGO_INITDB_ROOT_USER
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: user
