apiVersion: v1
kind: Service
metadata: 
  name: lb-service
  labels:
    author: kareem
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30005
  selector:
    type: webserver    
    
