---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    author: kareem
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: proxy
    author: kareem    
