---
apiVersion: v1
kind: Service
metadata: 
  name: newservice
  labels:
    author: kareem
spec:
  type: NodePort
  ports: 
    - targetPort:  80
      port: 8080
      nodePort: 30008
  selector:
    type: webserver
    author: kareem
