apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
    author: kareem
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
        version: v1
    spec:
       containers:
         - name: nginx
           image: nginx:1.21
           ports:
            - containerPort: 80
           volumeMounts:
             name: my-volume
             mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
     - metadata:
         name: my-volume
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
            requests:
              storage: 500Mi
      
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30016
  selector: 
    type: proxy
          

