---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: LoadBalancer
  ports: 
   - targetPort: 8080
     port: 8080
     nodePort: 30009
  selector:
    name: kareembhai1    
  
  
