---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontaine-app
  labels:
    author: kareembhai
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kareembhai
  template:
    metadata:
      labels:
        name: kareembhai
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 30009
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
             - matchExpressions:
                - key: slave1
                  operator: In
                  values:
                     - munna
