apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    type: db
    author: kareem
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mongodb-pod
      labels:
        type: db
    spec:
      containers:
        - name: mymongodb
          image: mongo
          ports:
            - containerPort: 27017  # Default MongoDB port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password

