---
apiVersion: v1
kind: Service
metadata:
  name: lb1-service
  labels: 
    author: kareem
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 30006
  selector:
        type: db
        author: kareem

