---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    author: kareem
spec:
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
       name: webserver
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata: 
  name: lb-service
  labels:
    author: kareem
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30010
  selector:
    name: webserver    
           
