---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
    author: kareem
spec:
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels: 
        type: proxy
    spec:
      containers:
       - name: nginx
         image: nginx
         ports:
          - containerPort: 80
         resources:
           requests:
             cpu: 300m
           limits:
             cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    author: kareem
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30009
  selector:
    type: proxy  
  
      
                 
