---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    author: kareem
spec:
  type: LoadBalancer
  ports:
    - name: mynginx
      targetPort: 80
      port: 8080    # The port on the nginx container
      nodePort: 30009   # Node port for accessing the service
    - name: tomcat
      targetPort: 8080
      port: 8081
      nodePort: 30008   # Node port for accessing the service
  selector:
        type: hello  # Ensure this matches the pod's label

