apiVersion: apps/v1
kind: Deployment
metadata: 
 name: nginx-deployment
 labels: 
   type: proxy
   author: kareem
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: proxy
  template:
    metadata:  
      labels:
        name: proxy
    spec:
     containers:
       - name: mynginx
         image: nginx:latest
         ports:
          - containerPort: 80
         volumeMounts:
           - name: my-volume
             mountPath: /usr/share/nginx/html
     volumes:
       - name: my-volume
         emptyDir: {}       


               

