---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    authoe: kareem
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: proxy
